"""добавил поля хэша в модель изображения

Revision ID: 6cc9558eab52
Revises: afb558f76671
Create Date: 2026-06-06 18:05:53.694207
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '6cc9558eab52'
down_revision: Union[str, None] = 'afb558f76671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cache_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_images_cache_key'), 'images', ['cache_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_cache_key'), table_name='images')
    op.drop_column('images', 'cache_key')
    # ### end Alembic commands ###
