"""добавил поля хэша в модель caption

Revision ID: c0e3e77a2778
Revises: 6cc9558eab52
Create Date: 2026-06-07 04:28:06.370343
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'c0e3e77a2778'
down_revision: Union[str, None] = '6cc9558eab52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captions', sa.Column('cache_key', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_captions_cache_key'), 'captions', ['cache_key'], unique=False)
    op.drop_index('ix_images_cache_key', table_name='images')
    op.drop_column('images', 'cache_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('cache_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_images_cache_key', 'images', ['cache_key'], unique=False)
    op.drop_index(op.f('ix_captions_cache_key'), table_name='captions')
    op.drop_column('captions', 'cache_key')
    # ### end Alembic commands ###
