"""hash in image model

Revision ID: dcbb3daacdb8
Revises: de69ef237e8b
Create Date: 2026-06-07 04:53:10.563627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'dcbb3daacdb8'
down_revision: Union[str, None] = 'de69ef237e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_images_image_hash'), 'images', ['image_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_hash'), table_name='images')
    op.drop_column('images', 'image_hash')
    # ### end Alembic commands ###
